[build]
  publish = "."

[build.environment]
  GIT_SUBMODULES = "false"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, immutable, max-age=31536000"

[[headers]]
  for = "/assets/music/*"
  [headers.values]
    Cache-Control = "public, immutable, max-age=31536000"

[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, immutable, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, must-revalidate, max-age=0"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, must-revalidate, max-age=0"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, must-revalidate, max-age=0"
